spring.application.name=NexaIoT Server

spring.mongodb.uri=${MONGODB_URI}

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# MQTT
mqtt.broker-url=tcp://localhost:1883
mqtt.client-id=nexaiot-server
mqtt.telemetry-topic=nexaiot/devices/+/telemetry
mqtt.state-topic=nexaiot/devices/+/state
mqtt.qos=1

alerts.temperature-high-threshold=30.0

